export const GET_DESTINATIONS = "GET_DESTINATIONS";
export const NEW_DESTINATION = "DELETE_DESTINATION";
export const DELETE_POST = "DELETE_POST";
export const GET_ERRORS = "GET_ERRORS";
export const DESTINATION_LOADING = "DESTINATION_LOADING";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
