export const GET_DESTINATIONS = "GET_DESTINATIONS";
export const NEW_DESTINATION = "NEW_DESTINATION";
export const DELETE_DESTINATION = "DELETE_DESTINATION";
export const GET_ERRORS = "GET_ERRORS";
export const DESTINATION_LOADING = "DESTINATION_LOADING";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
